### ISSUE TITLE
Automate the initial setup for Treadmill on my machine

### ISSUE THREAD

**Issue by snyaggarwal** [ThoughtWorksInc/treadmill#1]
So that 
I can get started with minimal effort
Tasks : 
"Pull a script from somewhere.
On invocation, the script provisions the box and installs treadmill.
Document it."
"Assumption:
We'll provision the box using 'vagrant'
We'll start off with shell-scripts but later migrate to Ansible."

**Comment by ankitabhopatkar13** [comment]
- Created a vagrant box image by running the provision.sh on the base centos box.
- Uploaded the vagrant box image on S3 and changed the VagrantFile to use the box image from S3.
- We need to start the zookeeper and create the cgroup folders manually after doing Vagrant Up.
- Updated the Readme.md file in standard_setup branch.

**Comment by ankitabhopatkar13** [comment]
@ceache 
The instructions for Vagrant setup has been added to the [Readme.md](https://github.com/ThoughtWorksInc/treadmill/blob/standard_setup/README.md). Please try it out and let us know the feedback.

**Comment by godsarmy** [comment]
I have to add below part to Vagrantfile, otherwise my VM will have 'cable disconnected' issue on my VM in the MACOS virtualbox.

```
 config.vm.provider :virtualbox do |vm|
    vm.customize [
        "modifyvm", :id,
        "--cableconnected1", "on",
    ]
  end
```
