### ISSUE TITLE
Bootstrap a node on a Treadmill cell

### ISSUE THREAD

**Issue by snyaggarwal** [ThoughtWorksInc/treadmill#4]
So that : 
I can later schedule nodes on the infrastructure
Tasks: 
"Provision the box for the node on AWS, if needed.
Ensure base Treadmill services are up and running.
Ensure the box is visible to the scheduler and zookeeper.

"
"Assumption:
This should work from any machine that has Treadmill in some form (e.g. built on developer box or installed on any box).
We're configuring a slave node.
We'll rely on Ansible to provision the box.
We rely on the existing Treadmill functionality to provision resources for the node.
We'll rely on 'infrastructure.yml' to specify the node identity and use the resource capacity that comes out of the box (cpu, disk, memory).
The EC2 instance resides on a public subnet, for now."

**Comment by ankitabhopatkar13** [comment]
Tasks
- [ ] Create EC2 box (and other things)
- [ ] Satisfy sys deps
- [ ] Build Treadmill
- [ ] Run Treadmill Services
- [ ] Run s6
- [ ] Run eventd & Appcfgmgr
- [ ] Check the state of everything
