### ISSUE TITLE
Master install problem

### ISSUE THREAD

**Issue by Xingskcs** [ThoughtWorksInc/treadmill#72]
1.After vagrant up --provision
   I run 
   treadmill admin install --profile vagrant master --master-id 1 --run
   report an error:
   Error: no such option: --profile

2.After removing --profile, reporting another error:
   s6-supervise (child): fatal: unable to exec run: No such file or directory
   s6-supervise host_tickets: warning: unable to spawn ./run - waiting 10 seconds

**Comment by rahulj** [comment]
The default treadmill installation inside vagrant image is not up to date. Please try running admin install command after [reinstalling treadmill](https://github.com/ThoughtWorksInc/treadmill/issues/73) within virtualenv.

**Comment by Xingskcs** [comment]
@rahulj Thank you! But after running "python setup.py install". I run:
 treadmill admin install --profile vagrant master --master-id 1 --run
Treadmill still reports the same error:
s6-supervise (child): fatal: unable to exec run: No such file or directory
s6-supervise host_tickets: warning: unable to spawn ./run - waiting 10 seconds

**Comment by Xingskcs** [comment]
@rahulj Thank you very much!
