### ISSUE TITLE
master can't be started up

### ISSUE THREAD

**Issue by Xingskcs** [ThoughtWorksInc/treadmill#77]
I use the newest treadmill.
After I run "vagrant up --provision master"
It reports error as follows:

Installing Virtualbox Guest Additions 5.1.22 - guest version is 4.3.28

An error occurred during installation of VirtualBox Guest Additions 5.1.22. Some                                                                   functionality may not work as intended.
In most cases it is OK that the "Window System drivers" installation failed.

Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   4.3.28
VBoxService inside the vm claims: 5.1.22
Going on, assuming VBoxService is correct...
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   4.3.28
VBoxService inside the vm claims: 5.1.22
Going on, assuming VBoxService is correct...
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   4.3.28
VBoxService inside the vm claims: 5.1.22
Going on, assuming VBoxService is correct...
Restarting VM to apply changes...

Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant

The error output from the command was:

/sbin/mount.vboxsf: mounting failed with the error: No such device

I think the errors may be caused by versions.
My version is:
virtualbox : 5.1.22
vagrant : 1.9.3
vagrant-vbguest : 0.14.2
The operating system of host machine is windows 10

So I want to ask if the errors are caused by versions?
What the versions are in your testing environment?
Thanks!

**Comment by snyaggarwal** [comment]
Can you try ``` vagrant plugin install vagrant-vbguest ```

**Comment by Xingskcs** [comment]
@snyaggarwal 
Thanks!
But it reports another error when starting up master:
## master: /tmp/vagrant-shell: /home/vagrant/treadmill/vagrant/scripts/_provision_master.sh: /bin/bash^M: bad interpreter: No such file or directory
master: /tmp/vagrant-shell: line 3: /home/vagrant/treadmill/vagrant/scripts/_provision_master.sh: Success
T## he SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

Do you know what went wrong?
Thanks!

**Comment by snyaggarwal** [comment]
not sure about this.
just to be sure if the provision was Green, can you try running 
``` vagrant reload master --provision ```

**Comment by Xingskcs** [comment]
@snyaggarwal 
Thanks!
