### ISSUE TITLE
Package Treadmill as a single binary

### ISSUE THREAD

**Issue by snyaggarwal** [ThoughtWorksInc/treadmill#8]
So that : 
I simplify the installation of Treadmill on any box
Tasks: 
"Generate cross platform binary for Treadmill.
Integrate with Tox for unit-testing side of things.
Optionally set up a pants build to generate the hermetically-sealed single binary.
Ensure file paths are correctly resolved using resource-streams.
Modify CI to push binaries to some S3 bucket.
Adjust the scripts to provision Treadmill on developer-box, EC2, etc."
"Dependency:
We need to way to incorporate custom plugins built for Treadmill on the outside.
Assumption:
Story '7024eb' has been played."

**Comment by GauravButola** [comment]
Considering that we have to make treadmill easy for the developers to use and deploy, we have zeroed down on the following approaches -

### Treadmill published as a python package on PyPi
We think it makes sense to make treadmill available on PyPi. Considering that treadmill is primarily a dev tool, developers would be most familiar and comfortable with installing treadmill through PyPi like every other python package.

In this approach working with treadmill would be as simple as running the commands -
`pip install treadmill # Install treadmill from PyPi`
`treadmill --help`
`treadmill aws cell --create # Provision a new aws cell`


### Treadmill as a pex binary
We explored [pex](https://github.com/pantsbuild/pex) as well which seems a good candidate for creating single, self contained treadmill binary. But there are some caveats to it as well -
* We'll have to create prebuilt binaries after each release for all the supported platforms; which requires a separate [pants](http://www.pantsbuild.org/) build system.
* It may not be easy for us to implement plugin architecture with pex as it creates a confined environment inside the binary. We have to verify this point though.
* If it's not an absolute requirement to have a downloadable treadmill binary file, then PyPi makes the most sense in our opinion.

**Comment by andreikeis** [comment]
I do not see treadmill is primary development tool. You will not call mesos or kubernetes development tool.

the fact that it is python is implementation detail - users do not interact with treadmill from python, will not import treadmill in their python code (except for generated python api, but same goes for java and scala).

as such, i think it makes more sense to keep treadmill as single binary.

i am sure it is possible to overcome the plugin issue. it can load core plugins from stream, and add-ons from python path, does not have to be single code path.

i am not against pypi, i think it is neat, and properly packaging treadmill as pypi will add install options for other environments. that said, i think pypi is secondary to single binary approach.

i am greedy - i want to have both :)

**Comment by snyaggarwal** [comment]
Thanks Andrie, we'll publish the package to PyPi as well then.
Again, we'd need official treadmill PyPi account, if there's any, so we can publish treadmill on MS' behalf.
